version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: Build
          command: npm run build
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: Unit Tests
          command: npm run test
  lint:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: Linting
          command: npm run lint
  prepare_deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Creating artifact
          command: npm run build:all
      - persist_to_workspace:
          root: ./deploy
          paths:
            - ./*
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - attach_workspace:
          at: ./
      - aws-cli/setup
      - run:
          name: Debugging
          command: ls -l
      - run:
          name: Deploying
          command: eb deploy
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
      - lint
      - prepare_deploy:
          requires:
            - build
      - deploy:
          requires:
            - prepare_deploy
